### PR TITLE
fix(eval): open the floating window under the cursor

### LINKED ISSUE #316: nvim dap ui eval floating window position
image
How can i make the floating window for `eval` under the cursor?

### PR DESCRIPTION
**Pull request by toh995**
Fixes #316 

Screenshot 2024-02-10 at 3 40 03 PM

### CODE REVIEW

File: lua/dapui/init.lua [hunk 1]
```diff
@@ -186,9 +186,11 @@ function dapui.eval(expr, args)
     prev_expr = expr
     local elem = dapui.elements.hover
     elem.set_expression(expr, args.context)
-    local line_no = async.fn.screenrow()
-    local col_no = async.fn.screencol()
```
Comment (toh995) [inline lua/dapui/init.lua:190]: `screenrow()` and `screencol()` always seem to output `1`.

See here: https://github.com/neovim/neovim/issues/15754#issuecomment-924905304

File: lua/dapui/init.lua [hunk 2]
```diff
@@ -186,9 +186,11 @@ function dapui.eval(expr, args)
...
-    local position = { line = line_no, col = col_no }
+    local win_pos = async.api.nvim_win_get_position(0)
+    local position = {
+      line = win_pos[1] + async.fn.winline(),
+      col = win_pos[2] + async.fn.wincol() - 1,
```
Comment (toh995) [inline lua/dapui/init.lua:192]: Fixes an off-by-one error 0-indexing vs. 1-indexing)

**Comment by rcarriga** [comment]
Thanks for the PR! :smile:
